CREATE TABLE achievement_info
(
    achievement_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT achievement_info_pkey PRIMARY KEY,
    description    varchar(255),
    logo_url       varchar(255),
    name           varchar(255)
);

CREATE TABLE film_info
(
    film_id bigint NOT NULL
        CONSTRAINT film_info_pkey PRIMARY KEY
);

CREATE TABLE global_role_info
(
    global_role_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT global_role_info_pkey PRIMARY KEY,
    name           varchar(255) UNIQUE
);

CREATE TABLE staff_info
(
    staff_id bigint NOT NULL
        CONSTRAINT staff_info_pkey PRIMARY KEY
);

CREATE TABLE user_info
(
    user_id           bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT user_info_pkey PRIMARY KEY,
    birthday          date,
    description       varchar(255),
    first_name        varchar(255),
    last_name         varchar(255),
    login             varchar(255) UNIQUE,
    logo_url          varchar(255),
    registration_date date
);

CREATE TABLE friendship_info
(
    user_id   bigint NOT NULL REFERENCES user_info,
    friend_id bigint NOT NULL REFERENCES user_info,
    CONSTRAINT friendship_info_pkey PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE user_achievements
(
    user_id        bigint NOT NULL REFERENCES user_info,
    achievement_id bigint NOT NULL REFERENCES achievement_info,
    CONSTRAINT user_achievements_pkey PRIMARY KEY (user_id, achievement_id)
);

CREATE TABLE user_favorite_films
(
    user_id bigint NOT NULL REFERENCES user_info,
    film_id bigint NOT NULL REFERENCES film_info,
    CONSTRAINT user_favorite_films_pkey PRIMARY KEY (user_id, film_id)
);

CREATE TABLE user_favorite_staffs
(
    user_id  bigint NOT NULL REFERENCES user_info,
    staff_id bigint NOT NULL REFERENCES staff_info,
    CONSTRAINT user_favorite_staffs_pkey PRIMARY KEY (user_id, staff_id)
);

CREATE TABLE user_global_roles
(
    user_id        bigint NOT NULL REFERENCES user_info,
    global_role_id bigint NOT NULL REFERENCES global_role_info,
    CONSTRAINT user_global_roles_pkey PRIMARY KEY (user_id, global_role_id)
);

CREATE TABLE user_pass
(
    user_password_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT user_pass_pkey PRIMARY KEY,
    password_hash    varchar(255),
    user_user_id     bigint REFERENCES user_info
);

CREATE TABLE user_want_watch_films
(
    user_id bigint NOT NULL REFERENCES user_info,
    film_id bigint NOT NULL REFERENCES film_info,
    CONSTRAINT user_want_watch_films_pkey PRIMARY KEY (user_id, film_id)
);

CREATE TABLE user_wanted_films
(
    user_id bigint NOT NULL REFERENCES user_info,
    film_id bigint NOT NULL REFERENCES film_info,
    CONSTRAINT user_wanted_films_pkey PRIMARY KEY (user_id, film_id)
);
